name: 'sign in Bot'
 
on:
  watch:
    types: started
  schedule:
  # 定时任务，在每天的5点推送登录信息到钉钉
    - cron: '0 16 * * *'
    - cron: '0 17 * * *'
jobs:
  bot:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python 3.1
      uses: actions/setup-python@v4
      with:
        python-version: 3.11.0
    - name: Set up Python
      uses: actions/setup-python@v4

      with:

       python-version: '3.11.0'

      # 安装依赖

    - name: Install dependencies

      run: |

       python -m pip install --upgrade pip

       pip install requests
    - name: Update paper list
      run: |
        python qd.py ${{ secrets.username }} ${{ secrets.password }} ${{ secrets.answer }} ${{ secrets.dingtalk_token }} 
